export const LANG_PDF = {
    es: {
        FULL_NAME: "Nombre completo",
        CURRICULUM_VITAE: "Currículum Vitae",
        PERSONAL_INFORMATION: "Información Personal:",
        DNI: "DNI: ",
        LOCATION: "Localidad: ",
        DATE_BIRTHDAY: "Fecha de Nacimiento: ",
        EMAIL: "Email: ",
        ACADEMIC_FORMATION: "Formación Académica: ",
        PROFESSIONAL_EXPERIENCE: "Experiencia Profesional: ",
        INSTITUTION: "Institución: ",
        DEGREE: "Título: ",
        START: "Inicio: ",
        END: "Fin: ",
        COMPANY: "Empresa: ",
        JOB_TITLE: "Puesto: ",
        ABILITIES: "Habilidades: ",
        HARD_SKILLS: "Competencias Técnicas:",
        SOFT_SKILLS: "Competencias Interpersonales:",
        OTHERS: "Otros: ",
        TITLE: "Título: ",
        LANGUAGE: "Lenguage",
        LANGUAGE2: "Idioma",
        TYPE_LABELS: {
            "Primary School": { es: "Escuela primaria:", en: "Primary School:" },
            "High School": { es: "Secundario:", en: "High School:" },
            "University": { es: "Universidades:", en: "Universities:" },
            "Course": { es: "Cursos:", en: "Courses:" },
            "Conference": { es: "Conferencia:", en: "Conference:" },
            "Other": { es: "Otro:", en: "Other:" }
        }
    },

    en: {
        FULL_NAME: "Full name",
        CURRICULUM_VITAE: "Curriculum Vitae",
        PERSONAL_INFORMATION: "Personal Information:",
        DNI: "DNI: ",
        LOCATION: "Location: ",
        DATE_BIRTHDAY: "Date of Birth: ",
        EMAIL: "Email: ",
        ACADEMIC_FORMATION: "Academic Background: ",
        PROFESSIONAL_EXPERIENCE: "Professional Experience: ",
        INSTITUTION: "Institution: ",
        DEGREE: "Degree: ",
        START: "Start: ",
        END: "End: ",
        COMPANY: "Company: ",
        JOB_TITLE: "Job Title: ",
        ABILITIES: "Skills: ",
        HARD_SKILLS: "Hard Skills",
        SOFT_SKILLS: "Soft Skills",
        OTHERS: "Others: ",
        TITLE: "Title: ",
        LANGUAGE: "Language",
        LANGUAGE2: "Language",
        TYPE_LABELS: {
            "Primary School": { en: "Primary School:", es: "Escuela primaria:" },
            "High School": { en: "High School:", es: "Secundario:" },
            "University": { en: "Universities:", es: "Universidades:" },
            "Course": { en: "Coursse:", es: "Cursos:" },
            "Conference": { en: "Conferences:", es: "Conferencias:" },
            "Other": { en: "Others:", es: "Otros:" }
        }
    }
};